"""Binding The Databases

Revision ID: ad80d3472492
Revises: 0eead5932faa
Create Date: 2022-04-12 01:06:51.897183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad80d3472492'
down_revision = '0eead5932faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essays', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'essays', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'essays', type_='foreignkey')
    op.drop_column('essays', 'author_id')
    # ### end Alembic commands ###
