"""Adding date_posted

Revision ID: b63deca1f6e6
Revises: ad80d3472492
Create Date: 2022-04-12 15:48:16.795730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63deca1f6e6'
down_revision = 'ad80d3472492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essays', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essays', 'date_posted')
    # ### end Alembic commands ###
