"""Added Database Sections

Revision ID: e41cfcb00df9
Revises: 
Create Date: 2022-04-10 16:23:26.438689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41cfcb00df9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('about_author', sa.Text(length=500), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'about_author')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
